spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/flash_bid
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true