spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  web:
    resources:
      static-locations: file:/Users/kotlinandnode/seungho/uploads/