create table auction_wish_list
(
    id         bigint generated by default as identity
        primary key,
    auction_id bigint,
    user_id    bigint,
    created_at timestamp(6)
);

create table account
(
    is_verified boolean           not null,
    login_type  smallint
        constraint account_login_type_check
            check ((login_type >= 0) AND (login_type <= 4)),
    point       integer default 0 not null,
    user_status smallint
        constraint account_user_status_check
            check ((user_status >= 0) AND (user_status <= 4)),
    user_type   smallint
        constraint account_user_type_check
            check ((user_type >= 0) AND (user_type <= 3)),
    created_at  timestamp(6),
    deleted_at  timestamp(6),
    id          bigint            not null
        primary key,
    updated_at  timestamp(6),
    description varchar(255),
    email       varchar(255)      not null,
    nickname    varchar(255),
    password    varchar(255),
    profile_url varchar(255),
    uuid        varchar(255)      not null
);

create table category
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    root_id    bigint
        constraint fk_category_root
            references category,
    updated_at timestamp(6),
    name       varchar(255)
);

create table delivery_info
(
    delivery_fee integer,
    id           bigint generated by default as identity
        primary key
);

create table feed
(
    view_count integer,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    user_id    bigint
        constraint fk_feed_user
            references account,
    contents   text
);

create table comments
(
    created_at timestamp(6),
    feed_id    bigint
        constraint fk_comments_feed
            references feed,
    id         bigint generated by default as identity
        primary key,
    reply_id   bigint
        constraint fk_comments_reply
            references comments,
    updated_at timestamp(6),
    user_id    bigint
        constraint fk_comments_user
            references account,
    contents   varchar(255)
);

create table file
(
    file_type  smallint not null
        constraint file_file_type_check
            check ((file_type >= 0) AND (file_type <= 5)),
    created_at timestamp(6),
    file_id    bigint,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    user_id    bigint
        constraint fk_file_user
            references account,
    extension  varchar(255),
    file_name  varchar(255),
    url        varchar(255)
);

create table follow
(
    created_at   timestamp(6),
    follower_id  bigint
        constraint fk_follow_follower
            references account,
    following_id bigint
        constraint fk_follow_following
            references account,
    id           bigint generated by default as identity
        primary key,
    constraint follow_uk
        unique (follower_id, following_id)
);

create table goods
(
    delivery_type smallint not null
        constraint goods_delivery_type_check
            check ((delivery_type >= 0) AND (delivery_type <= 2)),
    id            bigint generated by default as identity
        primary key,
    title         varchar(500),
    description   text
);

create table likes
(
    account_id bigint
        constraint fk_likes_account
            references account,
    created_at timestamp(6),
    feed_id    bigint
        constraint fk_likes_feed
            references feed,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    unique (account_id, feed_id)
);

create table notices
(
    view_count integer      not null,
    created_at timestamp(6) not null,
    id         bigint generated by default as identity
        primary key,
    category   varchar(255) not null,
    content    text         not null,
    title      varchar(255) not null
);

create table notification
(
    notification_type smallint
        constraint notification_notification_type_check
            check ((notification_type >= 0) AND (notification_type <= 2)),
    account_id        bigint
        constraint fk_notification_account
            references account,
    created_at        timestamp(6),
    id                bigint generated by default as identity
        primary key,
    updated_at        timestamp(6),
    content           varchar(255),
    link              varchar(255),
    title             varchar(255)
);

create table notification_read
(
    account_id      bigint
        constraint fk_notification_read_account
            references account,
    id              bigint generated by default as identity
        primary key,
    notification_id bigint
        constraint fk_notification_read_notification
            references notification,
    read_at         timestamp(6)
);

create table point_history
(
    charge_type  smallint not null
        constraint point_history_charge_type_check
            check ((charge_type >= 0) AND (charge_type <= 3)),
    earn_type    smallint
        constraint point_history_earn_type_check
            check ((earn_type >= 0) AND (earn_type <= 1)),
    earned_point integer  not null,
    created_at   timestamp(6),
    id           bigint generated by default as identity
        primary key,
    user_id_id   bigint
        constraint fk_point_history_user
            references account,
    contents     varchar(1024)
);

create table payment
(
    base_amount      integer      not null,
    charged_point    integer,
    final_amount     integer      not null,
    id               bigint generated by default as identity
        primary key,
    point_history_id bigint
        constraint fk_payment_point_history
            references point_history,
    purchase_at      timestamp(6) not null,
    user_id_id       bigint
        constraint fk_payment_user
            references account,
    status           varchar(20)  not null,
    method           varchar(50)  not null,
    order_id         varchar(255) not null,
    payment_key      varchar(255),
    receipt_id       varchar(255),
    receipt_url      varchar(255)
);

create table reply
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    user_id    bigint not null
        constraint fk_reply_user
            references account,
    content    text   not null
);

create table inquiry
(
    reply_status boolean      not null,
    created_at   timestamp(6),
    id           bigint generated by default as identity
        primary key,
    reply_id     bigint
        unique
        constraint fk_inquiry_reply
            references reply,
    updated_at   timestamp(6),
    user_id      bigint       not null
        constraint fk_inquiry_user
            references account,
    title        varchar(50)  not null,
    content      text         not null,
    inquiry_type varchar(255) not null
        constraint inquiry_inquiry_type_check
            check ((inquiry_type)::text = ANY
                   ((ARRAY ['GENERAL'::character varying, 'PAYMENT'::character varying, 'AUCTION'::character varying, 'ACCOUNT'::character varying, 'ETC'::character varying])::text[]))
);

create table trading_area
(
    latitude  real,
    longitude real,
    radius    real,
    id        bigint generated by default as identity
        primary key,
    address   varchar(255)
);

create table auction
(
    auction_status   smallint not null
        constraint auction_auction_status_check
            check ((auction_status >= 0) AND (auction_status <= 2)),
    auction_type     smallint not null
        constraint auction_auction_type_check
            check ((auction_type >= 0) AND (auction_type <= 1)),
    bid_unit         integer,
    count            integer,
    start_price      integer,
    view_count       integer,
    category_id      bigint
        constraint fk_auction_category
            references category,
    created_at       timestamp(6),
    delivery_info_id bigint
        unique
        constraint fk_auction_delivery
            references delivery_info,
    end_time         timestamp(6),
    goods_id         bigint
        constraint fk_auction_goods
            references goods,
    id               bigint   not null
        primary key,
    start_time       timestamp(6),
    trading_area_id  bigint
        unique
        constraint fk_auction_trading_area
            references trading_area,
    updated_at       timestamp(6),
    user_id          bigint
        constraint fk_auction_user
            references account
);

create table auction_participate
(
    auction_id     bigint
        constraint fk_auction_participate_auction
            references auction,
    id             bigint generated by default as identity
        primary key,
    join_time      timestamp(6),
    participant_id bigint
        constraint fk_auction_participate_user
            references account,
    unique (participant_id, auction_id)
);

create table auction_stats
(
    auction_id         bigint
        unique
        constraint fk_auction_stats_auction
            references auction,
    bidding_count      bigint,
    chat_count         bigint,
    id                 bigint not null
        primary key,
    last_bid_amount    bigint,
    last_bid_time      timestamp(6),
    participants_count bigint
);

create table auction_wishlist
(
    auction_id bigint
        constraint fk_auction_wishlist_auction
            references auction,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    user_id    bigint
        constraint fk_auction_wishlist_user
            references account,
    unique (auction_id, user_id)
);

create table auction_wishlist_count
(
    count bigint,
    id    bigint not null
        primary key
        constraint fk_auction_wishlist_count_auction
            references auction
);

create table bidding_log
(
    auction_id bigint
        constraint fk_bidding_log_auction
            references auction,
    bidder_id  bigint
        constraint fk_bidding_log_user
            references account,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    prev_price bigint,
    price      bigint
);

create table auction_chat
(
    chat_type      smallint not null
        constraint auction_chat_chat_type_check
            check ((chat_type >= 0) AND (chat_type <= 2)),
    auction_id     bigint
        constraint fk_auction_chat_auction
            references auction,
    bidding_log_id bigint
        constraint fk_auction_chat_bidding_log
            references bidding_log,
    created_at     timestamp(6),
    id             bigint generated by default as identity
        primary key,
    user_id        bigint
        constraint fk_auction_chat_user
            references account,
    contents       varchar(255)
);

create table confirm_bids
(
    auction_id     bigint
        unique
        constraint fk_confirm_bids_auction
            references auction,
    bidder_id      bigint
        constraint fk_confirm_bids_bidder
            references account,
    bidding_log_id bigint
        constraint fk_confirm_bids_bidding_log
            references bidding_log,
    created_at     timestamp(6),
    id             bigint generated by default as identity
        primary key,
    seller_id      bigint
        constraint fk_confirm_bids_seller
            references account
);

create table dm_room
(
    room_type  smallint not null
        constraint dm_room_room_type_check
            check ((room_type >= 0) AND (room_type <= 1)),
    auction_id bigint
        constraint fk_dm_room_auction
            references auction,
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    owner_id   bigint
        constraint fk_dm_room_owner
            references account,
    updated_at timestamp(6),
    room_name  varchar(30)
);

create table dm_chat
(
    dm_type     smallint not null
        constraint dm_chat_dm_type_check
            check ((dm_type >= 0) AND (dm_type <= 1)),
    created_at  timestamp(6),
    id          bigint generated by default as identity
        primary key,
    receiver_id bigint
        constraint fk_dm_chat_receiver
            references account,
    room_id     bigint
        constraint fk_dm_chat_room
            references dm_room,
    sender_id   bigint
        constraint fk_dm_chat_sender
            references account,
    contents    text
);

create table dm_chat_read
(
    dm_chat_id bigint
        constraint fk_dm_read_chat
            references dm_chat,
    id         bigint generated by default as identity
        primary key,
    read_at    timestamp(6),
    user_id    bigint
        constraint fk_dm_read_user
            references account,
    unique (dm_chat_id, user_id)
);

create table dm_image
(
    dm_id   bigint
        constraint fk_dm_image_chat
            references dm_chat,
    file_id bigint
        constraint fk_dm_image_file
            references file,
    id      bigint generated by default as identity
        primary key
);

create table dm_participate
(
    id          bigint generated by default as identity
        primary key,
    participate bigint
        constraint fk_dm_participate_user
            references account,
    room_id     bigint
        constraint fk_dm_participate_room
            references dm_room
);

create table feed_auction
(
    auction_id bigint
        constraint fk_feed_auction_auction
            references auction,
    feed_id    bigint
        constraint fk_feed_auction_feed
            references feed,
    id         bigint generated by default as identity
        primary key
);

create table feed_confirm_bid
(
    confirmed_bids_id bigint
        constraint fk_feed_confirm_bid_confirmed_bids
            references confirm_bids,
    feed_id           bigint
        constraint fk_feed_confirm_bid_feed
            references feed,
    id                bigint generated by default as identity
        primary key
);

create table user_fcm
(
    enabled    boolean,
    account_id bigint
        constraint fk_user_fcm_account
            references account,
    id         bigint generated by default as identity
        primary key,
    token      varchar(255)
);